### PR TITLE
Add `insert_with`

### PR DESCRIPTION
**Pull request by DasLixou**

### CODE REVIEW

**Comment by Ralith** [comment]
Why not use the existing [`vacant_key`](https://docs.rs/slab/latest/slab/struct.Slab.html#method.vacant_key) or `vacant_entry` methods?

**Comment by DasLixou** [comment]
I don't have much experience with the slab crate. I just started using it and expected a insert_with to exist

**Comment by Ralith** [comment]
Closures are generally more difficult to work with because they constrain control flow, and there's no widespread convention of a method with these semantics in Rust APIs. Do the existing APIs address your use case?

**Comment by DasLixou** [comment]
Yeah vacant entry would also do that in a more complicated way...

**Comment by Ralith** [comment]
If you'd prefer simpler, `vacant_key` is also good. Sounds like this isn't needed.

**Pull request closed without merging**
