### PR TITLE
Add serde support

### LINKED ISSUE #69: Make Slab serializable
I think this is as simple as slapping a `#[derive(Deserialize, Serialize)]` onto the `Slab` type.

### PR DESCRIPTION
**Pull request by PonasKovas**
Fixes #69

### CODE REVIEW

**Comment by PonasKovas** [comment]
is anyone even maintaining this old crate?

**Comment by taiki-e** [comment]
I'm not sure if it is good to serialize/deserialize all fields with derive. `len` (and probably `next`) can be calculated at deserialization, so I think it should be okay to skip serialize it.)

Personally, I'm starting to feel it may be good to serialize `Slab` as a map (key: `usize`, value: `T`). @carllerche Any thoughts?

**Comment by Ralith** [comment]
Serializing as a map seems more appropriate to me as well.

**Comment by hawkw** [comment]
FWIW, I don't think it makes sense to serialize the internal state of the slab, either. I think it probably ought to either be treated as a list (of just the occupied entries), or as a map of indices to entries. The map is probably the most correct representation.

**Pull request closed without merging**
